### ISSUE TITLE
Build summary should contain warning and bad links

### ISSUE THREAD

**Issue by koppor** [TechWiz-3/linksafe#10]
I think, the build summary could include the links, can't it?

In the current output, I don't know which links are bad.

![grafik](https://user-images.githubusercontent.com/1366654/196659091-a82884a9-8223-4bd1-8b47-488fb94203cb.png)

**Comment by TechWiz-3** [comment]
Thanks for this feedback, I definitely need to make this clearer, at the very bottom of the logs you will see:

<img width="1437" alt="Screen Shot 2022-10-19 at 8 56 52 pm" src="https://user-images.githubusercontent.com/75515581/196659977-143a4849-fc38-4f6b-9a9d-1ec7b2f4e4fb.png">

**Comment by TechWiz-3** [comment]
Would you like the failed links to be stored in the build summary as well?

**Comment by TechWiz-3** [comment]
@koppor ?

**Comment by koppor** [comment]
It's OK to have it in the bottom only. No need for the summary.
