### ISSUE TITLE
Update to Node 16

### ISSUE THREAD

**Issue by koppor** [TechWiz-3/linksafe#5]
I get following output when using this action:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout

See https://github.com/mattjegan/awesome-hacktoberfest/actions/runs/3222235089

Can you please update to Node 16?

**Comment by TechWiz-3** [comment]
Ah I believe I know what's happening, give me a few minutes please

**Comment by TechWiz-3** [comment]
OK, the issue is the workflow I pull requested uses `checkout@v2` which uses node.js 12. As it turns out, `checkout` in the workflow isn't even necessary, so to fix the issue, simply remove line `12` 👍

**Comment by TechWiz-3** [comment]
Any updates?

**Comment by koppor** [comment]
Yeah, works. Thank you!
